### ISSUE TITLE
GHC 8 support, provide explict encode/decode version.

### ISSUE THREAD

**Issue by winterland1989** [jonpetterbergman/binary-streams#1]
Thanks for making this library! I'd like to ask for a base version bump to support GHC 8, and add explict encode/decode version functions:

``` haskell
putToStream :: OutputStream ByteString -> Maybe Put -> IO () 
getFromStream :: InputStream ByteString -> Get a -> IO (Maybe a) 
```

Will you accept a PR?

**Comment by jonpetterbergman** [comment]
Hi, yes I will accept a PR regarding this.

I'm traveling ATM but will look at it when I get back home.

/Petter Bergman

2016-07-06 11:50 GMT+02:00 winterland notifications@github.com:

**Comment by winterland1989** [comment]
Sorry, but later i decide binary/lazy bytestrings combination really not work well with io-streams(or any other streamming libraries), the problem is that a streamming library will stream chunks of strict bytestrings, if we use binary to do encode/decode, we have to go through strict/lazy conversion in and out, so instead i write [cereal-streams](https://github.com/winterland1989/cereal-streams).
